# Generated by Django 4.2.18 on 2025-01-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[('draft', 0), ('published', 1)], default=0),
        ),
    ]
