# Generated by Django 4.2.18 on 2025-01-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
