# Generated by Django 4.2.18 on 2025-02-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_album_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
