# Generated by Django 4.2.18 on 2025-02-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_album_description_alter_album_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
    ]
