# Generated by Django 4.2.18 on 2025-02-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_album_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracklist',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
