# Generated by Django 4.2.18 on 2025-02-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_album_tracklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
