# Generated by Django 4.2.18 on 2025-02-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_alter_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='review.review'),
        ),
    ]
